// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (venue_id, guest_id, start_date, end_date, total_price, status)
VALUES ($1, $2, $3, $4, $5, 'PENDING')
RETURNING id, venue_id, guest_id, start_date, end_date, total_price, status, created_at
`

type CreateBookingParams struct {
	VenueID    int64          `json:"venue_id"`
	GuestID    int64          `json:"guest_id"`
	StartDate  pgtype.Date    `json:"start_date"`
	EndDate    pgtype.Date    `json:"end_date"`
	TotalPrice pgtype.Numeric `json:"total_price"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.VenueID,
		arg.GuestID,
		arg.StartDate,
		arg.EndDate,
		arg.TotalPrice,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.GuestID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const hasOverlappingBooking = `-- name: HasOverlappingBooking :one
SELECT EXISTS (
    SELECT 1 FROM bookings
    WHERE venue_id = $1
      AND status <> 'CANCELLED'
      AND daterange(start_date, end_date, '[)') && daterange($2::date, $3::date, '[)')
) AS overlaps
`

type HasOverlappingBookingParams struct {
	VenueID   int64       `json:"venue_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) HasOverlappingBooking(ctx context.Context, arg HasOverlappingBookingParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOverlappingBooking, arg.VenueID, arg.StartDate, arg.EndDate)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}

const lockVenueForBooking = `-- name: LockVenueForBooking :one

SELECT id, price_per_day FROM venues WHERE id = $1 FOR UPDATE
`

type LockVenueForBookingRow struct {
	ID          int64          `json:"id"`
	PricePerDay pgtype.Numeric `json:"price_per_day"`
}

// Primitivos do fluxo crítico de reserva. O use case roda os três dentro de uma
// única transação pgx:
//  1. LockVenueForBooking  (SELECT ... FOR UPDATE) — serializa concorrentes
//  2. HasOverlappingBooking — confere disponibilidade já com o lock segurado
//  3. CreateBooking — insere (a exclusion constraint é a rede de segurança)
//
// Pessimistic lock: chame DENTRO de uma tx para serializar tentativas
// concorrentes de reserva do mesmo espaço antes de checar disponibilidade.
func (q *Queries) LockVenueForBooking(ctx context.Context, id int64) (LockVenueForBookingRow, error) {
	row := q.db.QueryRow(ctx, lockVenueForBooking, id)
	var i LockVenueForBookingRow
	err := row.Scan(&i.ID, &i.PricePerDay)
	return i, err
}
