// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BookingStatus string

const (
	BookingStatusPENDING   BookingStatus = "PENDING"
	BookingStatusCONFIRMED BookingStatus = "CONFIRMED"
	BookingStatusCANCELLED BookingStatus = "CANCELLED"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type UserRole string

const (
	UserRoleGUEST UserRole = "GUEST"
	UserRoleHOST  UserRole = "HOST"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VenueStatus string

const (
	VenueStatusDRAFT     VenueStatus = "DRAFT"
	VenueStatusPUBLISHED VenueStatus = "PUBLISHED"
)

func (e *VenueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VenueStatus(s)
	case string:
		*e = VenueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VenueStatus: %T", src)
	}
	return nil
}

type NullVenueStatus struct {
	VenueStatus VenueStatus `json:"venue_status"`
	Valid       bool        `json:"valid"` // Valid is true if VenueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVenueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VenueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VenueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVenueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VenueStatus), nil
}

type Booking struct {
	ID         int64              `json:"id"`
	VenueID    int64              `json:"venue_id"`
	GuestID    int64              `json:"guest_id"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
	TotalPrice pgtype.Numeric     `json:"total_price"`
	Status     BookingStatus      `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Venue struct {
	ID          int64              `json:"id"`
	HostID      int64              `json:"host_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Capacity    int32              `json:"capacity"`
	PricePerDay pgtype.Numeric     `json:"price_per_day"`
	Address     string             `json:"address"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	City        string             `json:"city"`
	State       string             `json:"state"`
	Latitude    *float64           `json:"latitude"`
	Longitude   *float64           `json:"longitude"`
	Amenities   []string           `json:"amenities"`
	Status      VenueStatus        `json:"status"`
	Features    []string           `json:"features"`
}

type VenuePhoto struct {
	ID        int64              `json:"id"`
	VenueID   int64              `json:"venue_id"`
	ObjectKey string             `json:"object_key"`
	Url       string             `json:"url"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
