// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (user_id, booking_id, type)
VALUES ($1, $2, $3)
`

type CreateNotificationParams struct {
	UserID    int64  `json:"user_id"`
	BookingID int64  `json:"booking_id"`
	Type      string `json:"type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification, arg.UserID, arg.BookingID, arg.Type)
	return err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT n.id, n.type, n.read, n.created_at,
       n.booking_id, v.title AS venue_title, b.start_date, b.end_date
FROM notifications n
JOIN bookings b ON b.id = n.booking_id
JOIN venues v ON v.id = b.venue_id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT 20
`

type ListNotificationsByUserRow struct {
	ID         int64              `json:"id"`
	Type       string             `json:"type"`
	Read       bool               `json:"read"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	BookingID  int64              `json:"booking_id"`
	VenueTitle string             `json:"venue_title"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, userID int64) ([]ListNotificationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsByUserRow
	for rows.Next() {
		var i ListNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Read,
			&i.CreatedAt,
			&i.BookingID,
			&i.VenueTitle,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read = true WHERE user_id = $1 AND read = false
`

func (q *Queries) MarkNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, userID)
	return err
}
