// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVenuePhoto = `-- name: AddVenuePhoto :one
INSERT INTO venue_photos (venue_id, object_key, url, position)
VALUES ($1, $2, $3, $4)
RETURNING id, venue_id, object_key, url, position, created_at
`

type AddVenuePhotoParams struct {
	VenueID   int64  `json:"venue_id"`
	ObjectKey string `json:"object_key"`
	Url       string `json:"url"`
	Position  int32  `json:"position"`
}

func (q *Queries) AddVenuePhoto(ctx context.Context, arg AddVenuePhotoParams) (VenuePhoto, error) {
	row := q.db.QueryRow(ctx, addVenuePhoto,
		arg.VenueID,
		arg.ObjectKey,
		arg.Url,
		arg.Position,
	)
	var i VenuePhoto
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.ObjectKey,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
    host_id, title, description, capacity, price_per_day,
    address, neighborhood, city, state, complement, cep, latitude, longitude, amenities, features
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features, neighborhood, complement, cep
`

type CreateVenueParams struct {
	HostID       int64          `json:"host_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Capacity     int32          `json:"capacity"`
	PricePerDay  pgtype.Numeric `json:"price_per_day"`
	Address      string         `json:"address"`
	Neighborhood string         `json:"neighborhood"`
	City         string         `json:"city"`
	State        string         `json:"state"`
	Complement   string         `json:"complement"`
	Cep          string         `json:"cep"`
	Latitude     *float64       `json:"latitude"`
	Longitude    *float64       `json:"longitude"`
	Amenities    []string       `json:"amenities"`
	Features     []string       `json:"features"`
}

// Nasce como DRAFT (default da coluna status).
func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.HostID,
		arg.Title,
		arg.Description,
		arg.Capacity,
		arg.PricePerDay,
		arg.Address,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.Complement,
		arg.Cep,
		arg.Latitude,
		arg.Longitude,
		arg.Amenities,
		arg.Features,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.Capacity,
		&i.PricePerDay,
		&i.Address,
		&i.CreatedAt,
		&i.City,
		&i.State,
		&i.Latitude,
		&i.Longitude,
		&i.Amenities,
		&i.Status,
		&i.Features,
		&i.Neighborhood,
		&i.Complement,
		&i.Cep,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues WHERE id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVenue, id)
	return err
}

const deleteVenuePhoto = `-- name: DeleteVenuePhoto :exec
DELETE FROM venue_photos WHERE id = $1
`

func (q *Queries) DeleteVenuePhoto(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVenuePhoto, id)
	return err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features, neighborhood, complement, cep FROM venues WHERE id = $1
`

func (q *Queries) GetVenueByID(ctx context.Context, id int64) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.Capacity,
		&i.PricePerDay,
		&i.Address,
		&i.CreatedAt,
		&i.City,
		&i.State,
		&i.Latitude,
		&i.Longitude,
		&i.Amenities,
		&i.Status,
		&i.Features,
		&i.Neighborhood,
		&i.Complement,
		&i.Cep,
	)
	return i, err
}

const getVenuePhoto = `-- name: GetVenuePhoto :one
SELECT id, venue_id, object_key, url, position, created_at FROM venue_photos WHERE id = $1
`

func (q *Queries) GetVenuePhoto(ctx context.Context, id int64) (VenuePhoto, error) {
	row := q.db.QueryRow(ctx, getVenuePhoto, id)
	var i VenuePhoto
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.ObjectKey,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listPublishedPhotos = `-- name: ListPublishedPhotos :many
SELECT p.venue_id, v.title AS venue_title, p.url
FROM venue_photos p
JOIN venues v ON v.id = p.venue_id
WHERE v.status = 'PUBLISHED'
ORDER BY p.venue_id, p.position
LIMIT 30
`

type ListPublishedPhotosRow struct {
	VenueID    int64  `json:"venue_id"`
	VenueTitle string `json:"venue_title"`
	Url        string `json:"url"`
}

func (q *Queries) ListPublishedPhotos(ctx context.Context) ([]ListPublishedPhotosRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPhotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPhotosRow
	for rows.Next() {
		var i ListPublishedPhotosRow
		if err := rows.Scan(&i.VenueID, &i.VenueTitle, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuePhotoKeys = `-- name: ListVenuePhotoKeys :many
SELECT object_key FROM venue_photos WHERE venue_id = $1
`

func (q *Queries) ListVenuePhotoKeys(ctx context.Context, venueID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listVenuePhotoKeys, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuePhotos = `-- name: ListVenuePhotos :many
SELECT id, venue_id, object_key, url, position, created_at FROM venue_photos WHERE venue_id = $1 ORDER BY position, id
`

func (q *Queries) ListVenuePhotos(ctx context.Context, venueID int64) ([]VenuePhoto, error) {
	rows, err := q.db.Query(ctx, listVenuePhotos, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VenuePhoto
	for rows.Next() {
		var i VenuePhoto
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.ObjectKey,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuesByHost = `-- name: ListVenuesByHost :many
SELECT id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features, neighborhood, complement, cep FROM venues WHERE host_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVenuesByHost(ctx context.Context, hostID int64) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenuesByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.Description,
			&i.Capacity,
			&i.PricePerDay,
			&i.Address,
			&i.CreatedAt,
			&i.City,
			&i.State,
			&i.Latitude,
			&i.Longitude,
			&i.Amenities,
			&i.Status,
			&i.Features,
			&i.Neighborhood,
			&i.Complement,
			&i.Cep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishVenue = `-- name: PublishVenue :one
UPDATE venues SET status = 'PUBLISHED' WHERE id = $1 RETURNING id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features, neighborhood, complement, cep
`

func (q *Queries) PublishVenue(ctx context.Context, id int64) (Venue, error) {
	row := q.db.QueryRow(ctx, publishVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.Capacity,
		&i.PricePerDay,
		&i.Address,
		&i.CreatedAt,
		&i.City,
		&i.State,
		&i.Latitude,
		&i.Longitude,
		&i.Amenities,
		&i.Status,
		&i.Features,
		&i.Neighborhood,
		&i.Complement,
		&i.Cep,
	)
	return i, err
}

const searchPublishedVenues = `-- name: SearchPublishedVenues :many
SELECT
    v.id, v.title, v.description, v.capacity, v.price_per_day, v.city, v.state,
    COALESCE((SELECT p.url FROM venue_photos p WHERE p.venue_id = v.id ORDER BY p.position, p.id LIMIT 1), '')::text AS cover_url
FROM venues v
WHERE v.status = 'PUBLISHED'
  AND ($1::text = '' OR lower(v.city) = lower($1::text))
  AND ($2::int = 0 OR v.capacity >= $2::int)
  AND ($3::numeric = 0 OR v.price_per_day <= $3::numeric)
  AND ($4::text = '' OR v.title ILIKE '%' || $4::text || '%' OR v.description ILIKE '%' || $4::text || '%')
  AND (cardinality($5::text[]) = 0 OR v.amenities @> $5::text[])
  AND ($6::text = '' OR lower(v.state) = lower($6::text))
  AND ($7::numeric = 0 OR v.price_per_day >= $7::numeric)
  AND (
    $8::date IS NULL OR $9::date IS NULL OR NOT EXISTS (
      SELECT 1 FROM bookings b
      WHERE b.venue_id = v.id AND b.status <> 'CANCELLED'
        AND daterange(b.start_date, b.end_date, '[)') && daterange($8::date, $9::date, '[)')
    )
  )
ORDER BY v.created_at DESC
LIMIT 60
`

type SearchPublishedVenuesParams struct {
	City        string         `json:"city"`
	MinCapacity int32          `json:"min_capacity"`
	MaxPrice    pgtype.Numeric `json:"max_price"`
	Q           string         `json:"q"`
	Amenities   []string       `json:"amenities"`
	State       string         `json:"state"`
	MinPrice    pgtype.Numeric `json:"min_price"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
}

type SearchPublishedVenuesRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Capacity    int32          `json:"capacity"`
	PricePerDay pgtype.Numeric `json:"price_per_day"`
	City        string         `json:"city"`
	State       string         `json:"state"`
	CoverUrl    string         `json:"cover_url"`
}

// Listagem pública com filtros opcionais (sentinela vazio = sem filtro).
func (q *Queries) SearchPublishedVenues(ctx context.Context, arg SearchPublishedVenuesParams) ([]SearchPublishedVenuesRow, error) {
	rows, err := q.db.Query(ctx, searchPublishedVenues,
		arg.City,
		arg.MinCapacity,
		arg.MaxPrice,
		arg.Q,
		arg.Amenities,
		arg.State,
		arg.MinPrice,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPublishedVenuesRow
	for rows.Next() {
		var i SearchPublishedVenuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Capacity,
			&i.PricePerDay,
			&i.City,
			&i.State,
			&i.CoverUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues SET
    title         = $1,
    description   = $2,
    capacity      = $3,
    price_per_day = $4,
    address       = $5,
    neighborhood  = $6,
    city          = $7,
    state         = $8,
    complement    = $9,
    cep           = $10,
    latitude      = $11,
    longitude     = $12,
    amenities     = $13,
    features      = $14
WHERE id = $15
RETURNING id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features, neighborhood, complement, cep
`

type UpdateVenueParams struct {
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Capacity     int32          `json:"capacity"`
	PricePerDay  pgtype.Numeric `json:"price_per_day"`
	Address      string         `json:"address"`
	Neighborhood string         `json:"neighborhood"`
	City         string         `json:"city"`
	State        string         `json:"state"`
	Complement   string         `json:"complement"`
	Cep          string         `json:"cep"`
	Latitude     *float64       `json:"latitude"`
	Longitude    *float64       `json:"longitude"`
	Amenities    []string       `json:"amenities"`
	Features     []string       `json:"features"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.Title,
		arg.Description,
		arg.Capacity,
		arg.PricePerDay,
		arg.Address,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.Complement,
		arg.Cep,
		arg.Latitude,
		arg.Longitude,
		arg.Amenities,
		arg.Features,
		arg.ID,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.Capacity,
		&i.PricePerDay,
		&i.Address,
		&i.CreatedAt,
		&i.City,
		&i.State,
		&i.Latitude,
		&i.Longitude,
		&i.Amenities,
		&i.Status,
		&i.Features,
		&i.Neighborhood,
		&i.Complement,
		&i.Cep,
	)
	return i, err
}
