// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: venues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVenuePhoto = `-- name: AddVenuePhoto :one
INSERT INTO venue_photos (venue_id, object_key, url, position)
VALUES ($1, $2, $3, $4)
RETURNING id, venue_id, object_key, url, position, created_at
`

type AddVenuePhotoParams struct {
	VenueID   int64  `json:"venue_id"`
	ObjectKey string `json:"object_key"`
	Url       string `json:"url"`
	Position  int32  `json:"position"`
}

func (q *Queries) AddVenuePhoto(ctx context.Context, arg AddVenuePhotoParams) (VenuePhoto, error) {
	row := q.db.QueryRow(ctx, addVenuePhoto,
		arg.VenueID,
		arg.ObjectKey,
		arg.Url,
		arg.Position,
	)
	var i VenuePhoto
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.ObjectKey,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
    host_id, title, description, capacity, price_per_day,
    address, city, state, latitude, longitude, amenities, features
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features
`

type CreateVenueParams struct {
	HostID      int64          `json:"host_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Capacity    int32          `json:"capacity"`
	PricePerDay pgtype.Numeric `json:"price_per_day"`
	Address     string         `json:"address"`
	City        string         `json:"city"`
	State       string         `json:"state"`
	Latitude    *float64       `json:"latitude"`
	Longitude   *float64       `json:"longitude"`
	Amenities   []string       `json:"amenities"`
	Features    []string       `json:"features"`
}

// Nasce como DRAFT (default da coluna status).
func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.HostID,
		arg.Title,
		arg.Description,
		arg.Capacity,
		arg.PricePerDay,
		arg.Address,
		arg.City,
		arg.State,
		arg.Latitude,
		arg.Longitude,
		arg.Amenities,
		arg.Features,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.Capacity,
		&i.PricePerDay,
		&i.Address,
		&i.CreatedAt,
		&i.City,
		&i.State,
		&i.Latitude,
		&i.Longitude,
		&i.Amenities,
		&i.Status,
		&i.Features,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues WHERE id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVenue, id)
	return err
}

const deleteVenuePhoto = `-- name: DeleteVenuePhoto :exec
DELETE FROM venue_photos WHERE id = $1
`

func (q *Queries) DeleteVenuePhoto(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVenuePhoto, id)
	return err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features FROM venues WHERE id = $1
`

func (q *Queries) GetVenueByID(ctx context.Context, id int64) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.Capacity,
		&i.PricePerDay,
		&i.Address,
		&i.CreatedAt,
		&i.City,
		&i.State,
		&i.Latitude,
		&i.Longitude,
		&i.Amenities,
		&i.Status,
		&i.Features,
	)
	return i, err
}

const getVenuePhoto = `-- name: GetVenuePhoto :one
SELECT id, venue_id, object_key, url, position, created_at FROM venue_photos WHERE id = $1
`

func (q *Queries) GetVenuePhoto(ctx context.Context, id int64) (VenuePhoto, error) {
	row := q.db.QueryRow(ctx, getVenuePhoto, id)
	var i VenuePhoto
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.ObjectKey,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listPublishedVenues = `-- name: ListPublishedVenues :many
SELECT
    v.id, v.title, v.description, v.capacity, v.price_per_day, v.city, v.state,
    COALESCE((SELECT p.url FROM venue_photos p WHERE p.venue_id = v.id ORDER BY p.position, p.id LIMIT 1), '')::text AS cover_url
FROM venues v
WHERE v.status = 'PUBLISHED'
ORDER BY v.created_at DESC
LIMIT 60
`

type ListPublishedVenuesRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Capacity    int32          `json:"capacity"`
	PricePerDay pgtype.Numeric `json:"price_per_day"`
	City        string         `json:"city"`
	State       string         `json:"state"`
	CoverUrl    string         `json:"cover_url"`
}

// Listagem pública da home: só publicados, com a foto de capa (1ª foto).
func (q *Queries) ListPublishedVenues(ctx context.Context) ([]ListPublishedVenuesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedVenuesRow
	for rows.Next() {
		var i ListPublishedVenuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Capacity,
			&i.PricePerDay,
			&i.City,
			&i.State,
			&i.CoverUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuePhotoKeys = `-- name: ListVenuePhotoKeys :many
SELECT object_key FROM venue_photos WHERE venue_id = $1
`

func (q *Queries) ListVenuePhotoKeys(ctx context.Context, venueID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listVenuePhotoKeys, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuePhotos = `-- name: ListVenuePhotos :many
SELECT id, venue_id, object_key, url, position, created_at FROM venue_photos WHERE venue_id = $1 ORDER BY position, id
`

func (q *Queries) ListVenuePhotos(ctx context.Context, venueID int64) ([]VenuePhoto, error) {
	rows, err := q.db.Query(ctx, listVenuePhotos, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VenuePhoto
	for rows.Next() {
		var i VenuePhoto
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.ObjectKey,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuesByHost = `-- name: ListVenuesByHost :many
SELECT id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features FROM venues WHERE host_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVenuesByHost(ctx context.Context, hostID int64) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenuesByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.Description,
			&i.Capacity,
			&i.PricePerDay,
			&i.Address,
			&i.CreatedAt,
			&i.City,
			&i.State,
			&i.Latitude,
			&i.Longitude,
			&i.Amenities,
			&i.Status,
			&i.Features,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishVenue = `-- name: PublishVenue :one
UPDATE venues SET status = 'PUBLISHED' WHERE id = $1 RETURNING id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features
`

func (q *Queries) PublishVenue(ctx context.Context, id int64) (Venue, error) {
	row := q.db.QueryRow(ctx, publishVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.Capacity,
		&i.PricePerDay,
		&i.Address,
		&i.CreatedAt,
		&i.City,
		&i.State,
		&i.Latitude,
		&i.Longitude,
		&i.Amenities,
		&i.Status,
		&i.Features,
	)
	return i, err
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues SET
    title         = $1,
    description   = $2,
    capacity      = $3,
    price_per_day = $4,
    address       = $5,
    city          = $6,
    state         = $7,
    latitude      = $8,
    longitude     = $9,
    amenities     = $10,
    features      = $11
WHERE id = $12
RETURNING id, host_id, title, description, capacity, price_per_day, address, created_at, city, state, latitude, longitude, amenities, status, features
`

type UpdateVenueParams struct {
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Capacity    int32          `json:"capacity"`
	PricePerDay pgtype.Numeric `json:"price_per_day"`
	Address     string         `json:"address"`
	City        string         `json:"city"`
	State       string         `json:"state"`
	Latitude    *float64       `json:"latitude"`
	Longitude   *float64       `json:"longitude"`
	Amenities   []string       `json:"amenities"`
	Features    []string       `json:"features"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.Title,
		arg.Description,
		arg.Capacity,
		arg.PricePerDay,
		arg.Address,
		arg.City,
		arg.State,
		arg.Latitude,
		arg.Longitude,
		arg.Amenities,
		arg.Features,
		arg.ID,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.Capacity,
		&i.PricePerDay,
		&i.Address,
		&i.CreatedAt,
		&i.City,
		&i.State,
		&i.Latitude,
		&i.Longitude,
		&i.Amenities,
		&i.Status,
		&i.Features,
	)
	return i, err
}
